# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170525_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
