# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
